import './components/burger'
import './components/slider-ufa-defectoscopist'
import './components/slider-delivery-geography'
import './components/slider-product-page'
import './components/slider'
import './components/tabs'
